# Generated by Django 3.1.7 on 2021-02-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('asentamiento', models.CharField(max_length=60)),
                ('tipo_asentamiento', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=35)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=25)),
                ('zona', models.CharField(max_length=20)),
            ],
        ),
    ]
